# 注意：这是一个GNU Makefile。您必须使用“gmake”而不是“make”。
#
# 线程作业的Makefile。线程作业必须
#  首先完成！


ifndef MAKEFILE_THREADS
define MAKEFILE_THREADS
yes
endef

include Makefile.local
include ../Makefile.common

endif # MAKEFILE_THREADS