# 这是GNU-Makefile的一部分，用于指定系统相关的
# Makefile环境部分。

# 这部分会作为GNU-Makefile的一部分被包含在每个
# 子目录中。

# 滑铁卢的修改应该使得选择正确的机器
# 定义变得自动化。您不需要为
# MIPS机器（cantor.math）或SPARC（descartes，napier，
# cayley，...）编辑此文件。

ifndef MAKEFILE_DEP
define MAKEFILE_DEP
yes
endef

# 这些定义可能会随着软件的更新而改变。
# 其中一些也是系统相关的
CPP=/lib/cpp
CC = g++
LD = g++
AS = as

uname = $(shell uname)

mips_arch = dec-mips-ultrix

# DEC MIPS，Ultrix
ifeq ($(uname),ULTRIX)
HOST := -DHOST_MIPS
arch = $(mips_arch)
CPPFLAGS = -P $(INCDIR) $(HOST)
ifdef MAKEFILE_TEST
LDFLAGS = -T script -N 
endif
endif

# SUN SPARC，Sun 4.xx 
ifeq ($(uname),SunOS)
HOST := -DHOST_SPARC -DHOST_IS_BIG_ENDIAN
arch = sun-sparc-sunos
CPPFLAGS = $(INCDIR) $(HOST)
ifdef MAKEFILE_TEST
GCCDIR = /software/gcc_nachos/bin/decstation-ultrix-
LDFLAGS = -T script -N
ASFLAGS = -mips2
endif
endif

# HP PA-RISC，HP_UX
# 注意：我没有访问HP，所以我不知道
#       uname在这里实际输出什么...
ifeq ($(uname),HpUX)
HOST = -DHOST_SNAKE -DHOST_IS_BIG_ENDIAN
arch = parisc-hpux
endif

# 386，386BSD Unix或NetBSD Unix（可通过匿名ftp
#    从agate.berkeley.edu获取）
ifeq ($(uname),Linux)
HOST_LINUX=-linux
HOST = -DHOST_i386 -DHOST_LINUX
CPP=/sbin/cpp
CPPFLAGS = $(INCDIR) -D HOST_i386 -D HOST_LINUX
arch = unknown-i386-linux
ifdef MAKEFILE_TEST
#GCCDIR = /usr/local/nachos/bin/decstation-ultrix-
GCCDIR = /usr/local/mips/bin/decstation-ultrix-
LDFLAGS = -T script -N
ASFLAGS = -mips2
endif
endif

# 386 FreeBSD的轻微变体
ifeq ($(uname),386FreeBSD)
HOST = -DHOST_i386 -DFreeBSD
CPP=/usr/bin/cpp
arch = x86-freebsd
endif

# OSF在DEC Alpha上的实现，由David Bowers提供
ifeq ($(uname),OSF1)
HOST = -DHOST_ALPHA
CPPFLAGS = $(INCDIR) -D HOST_ALPHA
CPP=/usr/local/lib/gcc-lib/alpha-dec-osf4.0/2.7.2/cpp
arch = dec-alpha-osf
ifdef MAKEFILE_TEST
GCCDIR = /home/unit/66204/gcc/bin/decstation-ultrix-
LDFLAGS = -T script -N
ASFLAGS = -mips2
endif
endif

arch_dir = arch/$(arch)
obj_dir = $(arch_dir)/objects
bin_dir = $(arch_dir)/bin
depends_dir = $(arch_dir)/depends


# 32/64位编译器相关选项。2021年8月5日

longbit = $(shell getconf LONG_BIT)

ifeq ($(longbit),64)
GCCOPT32 = -m32
ifndef MAKEFILE_TEST
ASOPT32 = --32
endif
endif


endif # MAKEFILE_DEP
