# 注意：这是一个GNU Makefile。你必须使用“gmake”而不是“make”。
#
# 网络作业的Makefile
#    定义设置，假设此作业是最后完成的 
#

ifndef MAKEFILE_NETWORK
define MAKEFILE_NETWORK
yes
endef

# 要更改作业的顺序，请相应地更改以下包含的顺序。

include ../threads/Makefile.local
include ../userprog/Makefile.local
#include ../vm/Makefile.local
include ../filesys/Makefile.local
include ../network/Makefile.local

include ../Makefile.dep
include ../Makefile.common

endif #MAKEFILE_NETWORK
