# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".
#
# Makefile for the threads assignment.  The threads assignment must
#  be done first!
#

ifndef MAKEFILE_THREADS
define MAKEFILE_THREADS
yes
endef

include Makefile.local
include ../Makefile.common

endif # MAKEFILE_THREADS